# Generated by João Rossi on 2024-04-29 22:12
import uuid
from django.db import migrations, models


def populate_uuid_dispositivo(apps, schema_editor):
    Dispositivo = apps.get_model('dispositivo', 'Dispositivo')
    for dispositivo in Dispositivo.objects.all():
        dispositivo.uuid = uuid.uuid4()
        dispositivo.save()


def populate_uuid_coordenada(apps, schema_editor):
    Coordenada = apps.get_model('dispositivo', 'Coordenada')
    for coordenada in Coordenada.objects.all():
        coordenada.uuid = uuid.uuid4()
        coordenada.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0003_rename_description_dispositivo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(populate_uuid_dispositivo),
        migrations.RemoveField(
            model_name='dispositivo',
            name='id',
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(populate_uuid_coordenada),
        migrations.RemoveField(
            model_name='coordenada',
            name='id',
        ),
        migrations.RenameField(
            model_name='coordenada',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='coordenada',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
