# Generated by Django 5.0.3 on 2024-05-02 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0003_rename_description_dispositivo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenada',
            name='data_hora_inclusao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='dispositivo',
            field=models.ForeignKey(blank=True, default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivo.dispositivo'),
        ),
        migrations.AlterField(
            model_name='coordenada',
            name='data_hora_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordenada',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
