# Generated by Django 5.0.3 on 2024-05-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0004_coordenada_data_hora_inclusao_coordenada_dispositivo_and_more'),
        ('dispositivo', '0004_uuid'),
    ]

    operations = [
    ]
