# Generated by Django 5.0.3 on 2024-05-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0006_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='modelo_veiculo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.CharField(max_length=20),
        ),
    ]
