# Generated by Django 5.0.3 on 2024-05-08 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0007_alter_veiculo_modelo_veiculo_alter_veiculo_placa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenada',
            name='veiculo',
            field=models.ForeignKey(blank=True, default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivo.veiculo'),
        ),
    ]
